[main.yml] Updated to openwrt-18.06 #16
openwisp/ansible-openwisp2-imagegenerator pull request #17
Opened 2018-11-06 15:03 UTC by EdgeKing810

Updated 'lede' with openwrt-18.06 and added some more packages. 

Please let me know if I have followed the guidelines well this time.

2018-11-06 16:06 UTC, hispanico requested changes
See my inline comments.

2018-11-06 16:06 UTC, hispanico commented on defaults/main.yml
> +      branch: openwrt-18.06
Are you sure this feed is needed as default?

2018-11-06 16:06 UTC, hispanico commented on defaults/main.yml
> +    - luci-ssl
These are custom packages. We shoudn't need as default.

2018-11-06 16:14 UTC, nemesisdesign commented on defaults/main.yml
> +      branch: openwrt-18.06
not needed

2018-11-06 16:15 UTC, nemesisdesign commented on defaults/main.yml
> +    - luci-ssl
exactly, we don't need these additions in this patch

2018-11-06 16:16 UTC, nemesifier requested changes
You did the pull request title well but not the commit message, update the commit message to:

```
[main.yml] Updated to openwrt-18.06 #16

Closes #16 
```

2018-11-06 17:01 UTC, EdgeKing810 commented
![image](https://user-images.githubusercontent.com/42406341/48080296-be964380-e206-11e8-9d6c-6479694d35c3.png)

Sorry, I was basing myself on the links provided on the links provided here: https://github.com/openwisp/ansible-openwisp2-imagegenerator/issues/16 

I did what you asked me to do in my last commit. Is there still anything more that needs to be done?

Closes #16

2018-11-06 18:26 UTC, hispanico commented
No worries.
Just a last step, could you squash and rename your commits as @nemesisdesign suggest?
```
[main.yml] Updated to openwrt-18.06
```

2018-11-07 03:14 UTC, EdgeKing810 commented
And... it's done. Should I squash all commits for future tasks too as well now?

2018-11-07 08:31 UTC, nemesifier approved these changes

2018-11-07 08:31 UTC, merged